### PR TITLE
spell error

### PR DESCRIPTION
**Pull request by fengpeiyuan**
words spell mistake

### CODE REVIEW

**Comment by wtarreau** [comment]
On Fri, Jan 15, 2016 at 12:49:53AM -0800, fengpeiyuan wrote:

> words spell mistake

I adjusted the commit message and applied it. Thanks.

Willy

**Comment by lukastribus** [comment]
Is "To walk around" instead of "To workaround" ["... the problem"] really what we want to use here? "To workaround" seems quite right to me.

**Comment by wtarreau** [comment]
On Fri, Jan 15, 2016 at 01:01:44AM -0800, Lukas Tribus wrote:

> Is "To walk around" instead of "To workaround" ["... the problem"] really
> what we want to use here? "To workaround" seems quite right to me.

Ah crap I didn't notice this one, I only saw the "adn"->"and" :-(
The correct form is "to work around" (eg: "He works around" and
not "He workarounds"). But the noun is "a workaround".

Thanks.

Willy

**Comment by fengpeiyuan** [comment]
Sorry, my spelling mistake. The correct form is "work around", not is "walk around".

**Pull request closed without merging**
